### ISSUE TITLE
Error: Cannot find module ... Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by megu01s** [virdpool/miner#1]
Hello,
I'm having some trouble on pool, I was able to do data_dir and tune a bit but when I start virdpool, I get this message 
: Error: Cannot find module '/home/megu/arweave/arweave/miner/node_modules/fy/lib/index.js'. Please verify that the package.json has a valid "main" entry
But there's isnt a lib folder in my arweave miner archive ? (see screenshot)
what can I do to fix it ? 
I looked around a bit and my package.json has the same script as the one in your list 'init'.
Thank you !

![Screenshot from 2021-05-26 13-28-33](https://user-images.githubusercontent.com/84707508/119652753-c9e20680-be26-11eb-995c-808e23cf7e5c.png)
![Screenshot from 2021-05-26 13-28-48](https://user-images.githubusercontent.com/84707508/119652757-ca7a9d00-be26-11eb-9b52-dc786cfcdbd4.png)

**Comment by vird** [comment]
Can you provide install log?

**Comment by megu01s** [comment]
Hi again, 
I did some research and appear that npm ci didn't work for my OS (ubuntu 20.04). I went back to read your miner/README.md for the 10th time and I learned to read : # NOTE some OS doesn't correctly work with npm ci
# see ./install_wsl.sh for workaround with pre-built node_modules
# Also you can use npm ci --unsafe-perm
I completely re-installed the whole miner and it did, now I have every folder, including the lib folder + index.json.
If anyone come across this... well here it is.

Sorry for the trouble and thank you!!
