### ISSUE TITLE
Check Port in run.sh problem?

### ISSUE THREAD

**Issue by Meatball13** [virdpool/miner#12]
I noticed in lines 13 to 18 in run.sh you have the following:

```
PORT="1984"

if [ `lsof -i -P -n | grep LISTEN | grep 1984 | wc -l` != "0" ]; then
  echo "FUCK 1984 port is occupied. Probably by other arweave node. I'm going to use 1985"
  PORT="1985"
fi
```

Shouldn't the 'grep' (and other references to 1984) look for the PORT variable as opposed to hardcoding port 1984 in there?  If someone changes their port using the PORT variable because they already have 1984 in use, the PORT will get set to 1985 as opposed to whatever they put in for the PORT var.

**Comment by vird** [comment]
It was simple failover if miner was already using arweave node and wants to launch arweave miner with virdpool patch
Not it's less simple but still simple failover with possibility to change PORT and multiple PORT+1 check.
Still can break, but I guess it will be enough for 99+% of cases
https://github.com/virdpool/miner/commit/24f3fad2abba9932a7bb4bc007ef9f85f7db6ba1#diff-d31ce0453051853c17ba2a5225b3d1bfab548e095bab0967d6acfd1b3ce1b35d
