### ISSUE TITLE
Feature Request: Add MSR Mod to miner

### ISSUE THREAD

**Issue by Meatball13** [virdpool/miner#13]
Not sure if it's even possible, but would there be any way to add the MSR mod (https://github.com/xmrig/xmrig/blob/dev/scripts/randomx_boost.sh) to boost hash rates in the miner package?

**Comment by vird** [comment]
I've added here
https://github.com/virdpool/miner/commit/6dd6c86cc0c755811190618f58f5480acd41fc2f#diff-d31ce0453051853c17ba2a5225b3d1bfab548e095bab0967d6acfd1b3ce1b35d
