### ISSUE TITLE
sync not work, can't download block

### ISSUE THREAD

**Issue by rosebush** [virdpool/miner#14]
neither start.sh nor sync.h can download blocks.
it's blocked after "Joined the Arweave network successfully."  but when use origin arweave to mine, it's works well.
what can i do ?

the error logs like this:

2021-10-19T09:14:25.524856+08:00 [warning] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_watchdog.erl:190 No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
2021-10-19T09:18:25.649809+08:00 [warning] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_bridge.erl:237 event: ar_bridge_update_peers_process_is_stuck
2021-10-19T09:26:25.651754+08:00 [warning] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_bridge.erl:237 event: ar_bridge_update_peers_process_is_stuck
2021-10-19T09:34:25.653761+08:00 [warning] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_bridge.erl:237 event: ar_bridge_update_peers_process_is_stuck
2021-10-19T09:42:25.655766+08:00 [warning] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_bridge.erl:237 event: ar_bridge_update_peers_process_is_stuck
2021-10-19T09:50:25.657737+08:00 [warning] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_bridge.erl:237 event: ar_bridge_update_peers_process_is_stuck
2021-10-19T09:58:25.659830+08:00 [warning] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_bridge.erl:237 event: ar_bridge_update_peers_process_is_stuck
2021-10-19T10:06:25.661747+08:00 [warning] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_bridge.erl:237 event: ar_bridge_update_peers_process_is_stuck

**Comment by vird** [comment]
This is not virdpool miner problem, but arweave node generic problem.
The only possible difference that this repo still uses 2.4.2, but upstream is 2.4.4
Try compare launch parameters especially peers

**Comment by rosebush** [comment]
thanks for your reply!
this is my parameters:

#origin arweave:
./bin/start mine mining_addr wNJP5uiI8mt3aHOd3Hi_XZZkcl3bB1y9x1hxvugvrY8 \
peer 188.166.200.45 peer 188.166.192.169 peer 163.47.11.64 peer 139.59.51.59 peer 138.197.232.192

#virdPool start
./arweave/_build/prod/rel/arweave/bin/start pool_mine \
  internal_api_secret oRfJfIYocqPfzZgGKkPhCtEKHsk \
  peer 188.166.200.45 peer 188.166.192.169 peer 163.47.11.64 peer 139.59.51.59 peer 138.197.232.192

and if only run vird_arweave with pool_mine parameter,and do not run proxy.coffee, could vird_arweave download blocks?

**Comment by vird** [comment]
> and if only run vird_arweave with pool_mine parameter,and do not run proxy.coffee, could vird_arweave download blocks?
Yes it should

N.b. I hope commands you specified either are 1-line, or have \

**Comment by rosebush** [comment]
yes, commands have \\, I forget to use double '\\'.

**Comment by rosebush** [comment]
"localhost:1984/info " like this:

{"network":"arweave.N.1","version":5,"release":46,"height":-1,"current":"not_joined","blocks":0,"peers":343,"queue_length":0,"node_state_latency":1}

"localhost:1984/peers"like this:

["127.0.0.9:1984","37.48.102.162:1984","165.227.36.199:1984","103.1.34.253:1984","94.130.135.178:1984","210.54.39.124:1984","8.216.1.185:1984","69.133.193.65:1984","66.181.34.117:1984","157.90.92.227:1984","178.62.222.154:1984","188.166.200.45:1984","157.90.92.225:1984","91.89.132.114:1984","164.90.129.157:1984","112.13.205.249:1984","5.79.71.150:1984","119.247.159.233:1984","184.153.71.213:1984","47.88.54.26:1984","117.18.99.40:1984","103.28.213.41:1984","65.21.6.25:1984","65.21.136.152:1984","220.133.191.45:1984","23.162.112.253:1984","112.13.92.94:1984","112.13.92.80:1984","112.13.92.83:1984","112.13.205.254:1984","112.13.92.79:1984","112.13.205.245:1984","112.13.92.88:1984","223.109.67.71:1984","112.13.205.246:1984","223.109.67.67:1984","111.0.38.163:1984","112.13.92.84:1984","111.0.38.169:1984","39.173.156.191:1984","111.0.38.160:1984","31.14.40.172:1984","112.13.92.93:1984","117.149.244.11:1984","111.0.38.161:1984","112.13.205.250:1984","112.13.92.91:1984","112.13.92.85:1984","39.173.177.117:1984","112.13.92.82:1984","112.13.205.251:1984","14.17.82.19:1984","72.224.114.63:1984","223.113.147.246:1984","49.87.177.132:1984","49.158.171.17:1984","111.0.38.164:1984","52.52.139.253:1984","14.116.138.103:1984","222.211.70.114:1984","122.147.47.106:1984","14.36.95.162:1984","47.110.40.36:1984","39.173.177.58:1984","39.173.177.249:1984","39.173.177.200:1984","39.173.176.6:1984","39.173.177.91:1984","39.173.176.44:1984","39.173.177.132:1984","39.173.177.207:1984","39.173.177.216:1984","39.173.177.205:1984","39.173.177.188:1984","39.173.176.52:1984","39.173.177.250:1984","112.13.90.184:1984","39.173.177.211:1984","39.173.177.96:1984","39.173.176.30:1984","39.173.177.164:1984","39.173.176.36:1984","39.173.177.232:1984","39.173.156.219:1984","39.173.176.59:1984","39.173.176.35:1984","39.173.176.27:1984","39.173.177.84:1984","39.173.177.78:1984","39.173.177.148:1984","39.173.176.7:1984","39.173.177.80:1984","39.173.177.108:1984","39.173.176.38:1984","39.173.176.21:1984","39.173.177.213:1984","39.173.177.179:1984","39.173.177.171:1984","39.173.177.114:1984","39.173.176.49:1984","39.173.176.5:1984","39.173.177.51:1984","39.173.177.95:1984","39.173.176.56:1984","39.173.176.20:1984","223.109.67.84:1984","39.173.177.254:1984","39.173.176.53:1984","39.173.176.24:1984","223.109.67.70:1984","112.49.45.137:1984","223.109.67.82:1984","39.173.177.83:1984","39.173.177.66:1984","39.173.177.173:1984","39.173.177.54:1984","116.207.131.37:1984","180.76.247.60:1984","117.18.99.45:1984","38.76.112.215:1984","39.173.177.79:1984","112.13.205.253:1984","39.173.156.213:1984","39.173.177.111:1984","218.212.176.208:1984","62.65.78.157:1984","39.173.177.142:1984","52.199.181.113:1984","111.0.38.162:1984","51.222.155.136:1984","39.173.177.121:1984","117.18.99.42:1984","39.173.176.22:1984","39.173.177.183:1984","39.173.177.99:1984","111.0.38.171:1984","216.166.16.59:1984","213.190.123.60:1984","175.209.244.39:1984","139.59.51.59:1984","73.230.76.78:1984","100.1.154.167:1984","113.56.45.102:1984","74.118.142.120:1984","144.126.136.232:1984","14.17.82.18:1984","39.173.177.172:1984","135.181.129.87:1984","86.7.219.105:1984","157.90.93.182:1984","112.13.205.247:1984","124.236.103.100:1984","157.90.92.234:1984","112.13.205.248:1984","65.21.226.175:1984","157.90.92.229:1984","60.191.139.247:1984","39.173.177.226:1984","39.173.177.222:1984","39.173.177.175:1984","107.181.87.18:1984","59.29.234.218:1984","157.230.2.154:1984","157.90.212.92:1984","208.167.253.95:1984","218.35.162.142:1984","14.17.82.20:1984","68.63.41.224:1984","73.247.5.147:1984","157.90.92.243:1984","157.90.92.226:1984","157.90.92.230:1984","157.90.92.223:1984","157.90.92.246:1984","65.21.75.42:1984","157.90.128.241:1984","160.45.66.156:1984","65.21.131.34:1984","39.173.176.10:1984","18.130.204.26:1984","157.90.92.232:1984","157.90.93.177:1984","39.173.177.97:1984","39.173.177.143:1984","65.21.33.240:1984","39.173.176.63:1984","39.173.156.214:1984","54.168.186.44:1984","71.163.168.207:1984","39.173.176.55:1984","65.21.202.108:1984","108.6.176.126:1986","39.173.177.189:1984","39.173.177.181:1984","39.173.177.220:1984","112.13.205.232:1984","73.15.70.67:1984","112.13.92.95:1984","39.173.176.51:1984","116.202.134.154:1984","157.90.92.239:1984","39.173.176.34:1984","139.59.19.218:1984","95.217.112.48:1984","51.195.254.19:1984","112.13.92.78:1984","111.0.38.166:1984","113.116.127.183:1984","157.90.92.224:1984","112.13.169.121:1984","134.209.180.114:1984","176.139.9.185:1984","72.186.50.15:1984","39.173.177.176:1984","39.173.177.252:1984","65.21.73.113:1984","157.90.93.179:1984","77.109.97.117:1984","68.36.60.77:1984","112.13.92.90:1984","39.173.177.102:1984","157.90.92.241:1984","108.6.176.126:1985","112.13.169.120:1984","39.173.177.246:1984","88.113.206.170:1984","69.130.186.33:1984","24.19.51.203:1984","99.171.136.198:1984","117.30.74.29:1984","124.244.190.136:1984","157.90.92.237:1984","159.196.109.74:1984","157.90.92.235:1984","223.113.147.2:1984","95.31.8.247:1984","78.186.154.164:1984","39.173.177.71:1984","65.21.136.93:1984","157.90.95.186:1984","157.90.92.236:1984","78.159.119.220:1984","139.99.173.170:1984","45.77.182.243:1984","112.13.92.87:1984","175.209.244.37:1984","108.6.176.126:1984","65.26.67.230:1984","112.13.92.81:1984","47.241.110.211:1984","187.106.245.66:1984","39.173.176.16:1984","39.173.177.87:1984","39.173.177.185:1984","39.173.177.219:1984","39.173.177.75:1984","39.173.177.204:1984","206.189.70.139:1984","65.21.121.160:1984","157.90.92.231:1984","51.68.175.166:1984","112.13.205.252:1984","183.110.233.3:1984","51.79.158.71:1984","39.173.177.113:1984","39.173.176.26:1984","135.181.178.95:1984","157.90.92.233:1984","223.113.147.3:1984","76.214.112.137:1984","61.6.3.242:1984","39.173.177.73:1984","39.173.177.126:1984","39.173.177.128:1984","157.230.45.221:1984","135.181.137.226:1984","135.181.137.241:1984","207.225.36.28:1984","111.249.96.39:1984","81.217.75.27:1984","114.222.107.85:1984","99.107.148.230:1984","39.173.176.70:1984","180.232.69.130:1984","39.173.177.93:1984","135.181.212.218:1984","157.90.93.249:1984","157.90.90.245:1984","157.90.92.159:1984","157.90.92.228:1984","95.217.195.99:1984","135.181.142.202:1984","159.89.236.26:1984","162.55.131.206:1984","146.59.34.254:1984","157.90.92.240:1984","84.250.160.41:1984","46.229.233.46:1981","157.230.102.219:1984","93.180.24.114:1984","76.64.82.67:1984","112.13.92.86:1984","46.229.233.46:1982","159.69.65.150:1984","171.5.134.157:1984","78.29.42.188:1984","5.9.68.26:1984","51.75.206.225:1984","88.97.79.124:1984","185.132.196.18:1984","151.59.5.138:1984","98.162.203.1:1986","46.229.233.46:1983","39.173.177.92:1984","39.173.177.221:1984","39.173.177.217:1984","157.90.92.245:1984","95.217.114.57:1984","51.178.91.117:1984","178.128.89.236:1984","96.41.132.201:1984","176.95.193.183:1984","72.18.38.198:1984","203.12.12.66:1984","198.251.89.25:1984","39.173.156.215:1984","39.173.176.19:1984","79.143.135.16:1984","104.248.251.82:1984","157.90.92.242:1984","157.90.92.244:1984","188.166.192.169:1984","162.55.247.44:1984","111.0.38.165:1984","109.108.71.9:1984","65.108.9.55:1984","102.182.137.162:1984","112.13.92.92:1984","39.173.176.66:1984","212.25.52.23:1984","39.173.177.101:1984","121.99.224.109:1984"]

what can I do to help this problem?

**Comment by vird** [comment]
Do you have all disks have > 20 GB free space?

**Comment by rosebush** [comment]
have 500G
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/sdc       ext4      251G  3.7G  235G   2% /
...
drvfs          9p        932G  408G  524G  44% /mnt/g

**Comment by vird** [comment]
Can you confirm that virdpool fork is consistently get you error "No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors." ?

**Comment by rosebush** [comment]
this is virdpool fork run 12hours log, there is no downloading log:

Launching Erlang Virtual Machine...
Exec: /mnt/g/arweave/virdpool/arweave/_build/prod/rel/arweave/erts-11.2/bin/erlexec -noshell -noinput +Bd -boot /mnt/g/arweave/virdpool/arweave/_build/prod/rel/arweave/releases/2.4.1.0/arweave -mode embedded -boot_var ERTS_LIB_DIR /mnt/g/arweave/virdpool/arweave/_build/prod/rel/arweave/lib -config /mnt/g/arweave/virdpool/arweave/_build/prod/rel/arweave/releases/2.4.1.0/sys.config -args_file /mnt/g/arweave/virdpool/arweave/_build/prod/rel/arweave/releases/2.4.1.0/vm.args -- foreground +Ktrue +A20 +SDio20 +sbwtvery_long +sbwtdcpuvery_long +sbwtdiovery_long +swtvery_low +swtdcpuvery_low +swtdiovery_low +Bi -run ar main mine mining_addr wNJP5uiI8mt3aHOd3Hi_WYYkcl3bB1y9x1hxvugvrY8 peer 188.166.200.45 peer 188.166.192.169 peer 163.47.11.64 peer 139.59.51.59 peer 138.197.232.192
Root: /mnt/g/arweave/virdpool/arweave/_build/prod/rel/arweave
/mnt/g/arweave/virdpool/arweave/_build/prod/rel/arweave
=INFO REPORT==== 26-Oct-2021::01:33:21.013505 ===
    alarm_handler: {set,{{disk_almost_full,"/init"},[]}}
=INFO REPORT==== 26-Oct-2021::01:33:21.013637 ===
    alarm_handler: {set,{{disk_almost_full,"/usr/lib/wsl/drivers"},[]}}
=INFO REPORT==== 26-Oct-2021::01:33:21.013711 ===
    alarm_handler: {set,{{disk_almost_full,"/usr/lib/wsl/lib"},[]}}
=INFO REPORT==== 26-Oct-2021::01:33:21.013778 ===
    alarm_handler: {set,{{disk_almost_full,"/mnt/c"},[]}}
=INFO REPORT==== 26-Oct-2021::01:33:21.013858 ===
    alarm_handler: {set,{{disk_almost_full,"/mnt/d"},[]}}
Downloading block index from 188.166.200.45:1984.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
Joining the Arweave network...
Initialising RandomX dataset for fast hashing. Swap height: 796000, Key: <<"_____7Q7GXkhWjuyJ22YFrYJVl3YtIT2cS7rdfIhGPg">>. The process may take several minutes.
RandomX dataset initialisation for swap height 796000 complete.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
2021-10-26T04:32:21.578745+08:00 [error] gen_server.erl:943 Generic server ar_wallets terminating. Reason: {{badmatch,{error,not_found}},[{ar_wallets,get_tree,2,[...]},{ar_wallets,'-handle_cast/2-fun-1-',3,...},{lists,foldl,...},{...}|...]}. Last message: {'$gen_cast',{init,[{block,<<31,...>>,<<...>>,...},{block,<<...>>,...},{block,...},{...}|...],[{138,197,...},{139,...}|...]}}. State: {#{<<>> => {sink,#{root => {no_parent,{0,nil},no_hash,no_prefix,...},size => 0},{0,not_set}}},<<>>,#{<<>> => {set,0,16...
2021-10-26T04:32:21.579200+08:00 [error] proc_lib.erl:525 crasher: initial call: ar_wallets:init/1, pid: <0.734.9>, registered_name: ar_wallets, error: {{badmatch,{error,not_found}},[{ar_wallets,get_tree,2,[{...}|...]},{ar_wallets,'-handle_cast/2-fun-1-',3,[...]},{lists,foldl,3,...},{ar_wallets,handle_cast,...},{gen_server,...}|...]}, ancestors: [ar_node_worker|...], message_queue_len: ..., messages: [], links: [<0.854.0>], dictionary: [], trap_exit: true, status: running, heap_size: 999631, stack_size:...
2021-10-26T04:32:21.583684+08:00 [error] /mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_node_worker.erl:274 event: unhandled_info, module: ar_node_worker, message: {'EXIT',<0.734.9>,{{badmatch,{error,not_found}},[{ar_wallets,get_tree,2,[{file,"/mnt/g/arweave/virdpool/arweave/apps/arweave/src/ar_wallets.erl"},{line,281}]},{ar_wallets,'-handle_cast/2-fun-1-',3,[{file,[...]},{line,...}]},{lists,foldl,3,[{file,...},{...}]},{ar_wallets,handle_cast,2,[{...}|...]},{gen_server,try_dispatch,4,...}|...]}}
Joined the Arweave network successfully.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
No foreign blocks received from the network or found by trusted peers. Please check your internet connection and the logs for errors.
2021-10-26T12:09:37.630689+08:00 [error] proc_lib.erl:525 crasher: initial call: gun:proc_lib_hack/5, pid: <0.18311.31>, registered_name: [], exit: {{{owner_gone,killed},[]},[{gun,proc_lib_hack,5,[{file,"/mnt/g/arweave/virdpool/arweave/_build/default/lib/gun/src/gun.erl"},{line,654}]},{proc_lib,init_p_do_apply,3,[{file,[...]},{line,...}]}]}, ancestors: [gun_sup|...], message_queue_len: ..., messages: [], links: [<0.739.0>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 2...
2021-10-26T12:09:37.631934+08:00 [error] supervisor.erl:722 Supervisor: {local,gun_sup}. Context: child_terminated. Reason: {{owner_gone,killed},[]}. Offender: id=gun,pid=<0.18311.31>.
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
Arweave Heartbeat: Server terminated safely.

-----

and this is origin fork log for 1 hour, :

Launching Erlang Virtual Machine...
Exec: /mnt/g/arweave/arweave-2.4.4.0/erts-11.1.7/bin/erlexec -noinput +Bd -boot /mnt/g/arweave/arweave-2.4.4.0/releases/2.4.4.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /mnt/g/arweave/arweave-2.4.4.0/lib -config /mnt/g/arweave/arweave-2.4.4.0/releases/2.4.4.0/sys.config -args_file /mnt/g/arweave/arweave-2.4.4.0/releases/2.4.4.0/vm.args -- foreground +Ktrue +A20 +SDio20 +sbwtvery_long +sbwtdcpuvery_long +sbwtdiovery_long +swtvery_low +swtdcpuvery_low +swtdiovery_low +Bi -run ar main mine mining_addr wNJP5uiI8mt3aHOd3Hi_WYYkcl3bB1y9x1hxvugvrY8 peer 188.166.200.45 peer 188.166.192.169 peer 163.47.11.64 peer 139.59.51.59 peer 138.197.232.192
Root: /mnt/g/arweave/arweave-2.4.4.0
/mnt/g/arweave/arweave-2.4.4.0
=INFO REPORT==== 26-Oct-2021::12:10:09.157052 ===
    alarm_handler: {set,{{disk_almost_full,"/init"},[]}}
=INFO REPORT==== 26-Oct-2021::12:10:09.157191 ===
    alarm_handler: {set,{{disk_almost_full,"/usr/lib/wsl/drivers"},[]}}
=INFO REPORT==== 26-Oct-2021::12:10:09.157270 ===
    alarm_handler: {set,{{disk_almost_full,"/usr/lib/wsl/lib"},[]}}
=INFO REPORT==== 26-Oct-2021::12:10:09.157355 ===
    alarm_handler: {set,{{disk_almost_full,"/mnt/c"},[]}}
=INFO REPORT==== 26-Oct-2021::12:10:09.157432 ===
    alarm_handler: {set,{{disk_almost_full,"/mnt/d"},[]}}
Joining the Arweave network...
Downloading block index from 139.59.51.59:1984.
Downloaded block index successfully.
Downloading joining block z0oUEUGnOCYRncs0lJOywnggfkvq_kv3ihJEA8Gkfl527HPEaU_3_J96IadcMZTR.
Initialising RandomX dataset for fast hashing. Swap height: 796000, Key: <<"_____7Q7GXkhWjuyJ22YFrYJVl3YtIT2cS7rdfIhGPg">>. The process may take several minutes.
RandomX dataset initialisation for swap height 796000 complete.
Downloading the block trail.
Downloading joining block orsceYIfo8AWwDPkX-vbDEFyURNC47zF1h6BwG14G5m2R1lcJ70mAzncDQV4QHzR.
Downloading joining block Vo_0bDPKU8CyrcP9CB328C59xqXMGhRcd7dYOIfTqjwBjQrzJlbnlIC8A8SrBV6h.
Downloading joining block 9tF1BGEGnsjH0zSxa6MAbILk4-KAPsdUk5iEUleDQPrfygmldMavgasKrPkmuhhH.
Downloading joining block uA8cNdNMt0jNeJr_k_SfDk1tskfeharPVv1_bfIu6pBT27sTMKAiGecTDjBleZMw.
Downloading joining block ONbiR2n1bv65VFZlNFxaX-mKBNQ6u5kl7rktjhykS-kE-C2IqH-9bEioX0sdy9e-.
Downloading joining block vgwLeh6JzLGE4HPGox5belus1J9AuUuzH8eyo57Gn7MGXQ2AP-3HtGi9qDlxXJ2-.
Downloading joining block MKAsiqpWkgSjh66U3x6frCRUD0RUD42_HyASRkSm029GYHSrMN4wz6uzGOEFdg2g.
Downloading joining block tn7MvgiLI_YD0pNMskqRvon5u47e0aZsp8LszmeKP2ru3lcP9V4-l7llk5wxKU44.
Downloading joining block 8tUvuy9-DvPZJDFjH7u8YmXybmTrtDPwvIi6BIVRLCNi7igJitzvfOm7ddw8MaRU.
Downloading joining block 4mvCm9NP6Rp7rT2IZFs9fVOJdNvWXkzzJJZSbGtn_zcIObY_5IjQd_u2o_Bfkmp-.
Downloading joining block 9kcgVO_VabtDND0y823nYXyVJXspE3PfYDBD8dde9M2z37VAbEVeL9ngP4lJf2dB.
Downloading joining block UjG0tkgaykWrsJ1uRNacjtPnD42AmleSL2IC7z9T_5jP6s44vai92p7cVyfntnm2.
Downloading joining block oRODOJAKzb5xaphEZal9rdPxMLPw8gDGPQNzH5MboMtaJd5UWbLqyl_hoPFUi9TT.
Downloading joining block RTc_rcQu-b2OcK9NF4VdfPMNL76-wilH_0C7coyoRykouM4ROvX7YtBlqxDqtT_y.
Downloading joining block mcQ48Suo7ArbWCjIAhQsq2ZJBZ3JTg9CVlYocQHBkW_goPGHTouE8jjcmwzaGxBV.
Downloading joining block s8eJfHgA3uHnYfHiTcxHJdZlFhERDDzDniRuYHCOvFBIWdbuA7Q7SFsP2eHUJxzk.
Downloading joining block VrBIvmkva35knIcaHZPvoiVa5I6pnPrdiyJ7Mbc-oP7Z4vPuYKJkbKixPPP-G1aa.
Downloading joining block ASMKeXoqORZfokRgT_KFv2O7fpY_MzPYKtlw6F5hCliD0-i1QKYQ9zMnzRWids7d.
Downloading joining block 98jhd0u_4oLeyP6d1DXMVu9dSXtfAlZVa7vueD4y1R5hJ6iBDnkHkcilfgl7ByQN.
Downloading joining block jB0aA5T6uin6iRZzTTV_aunYzTldR-fcB_WgXRNvRxAxKyB7VJGsxFo6b8TXyHeB.
Downloading joining block Pg8EvsGQ8Np01OQadLenq6-0h0_nd09jSc99iMOtPYoiyLFafYR82idVfvMdFPRy.
Downloading joining block OjMNf5OZwFwXCff5ilNvhHttr49TNn-5skOhF9BigP4zC-PUT4E05ZVK5HtmyF3x.
Downloading joining block m7YhQ4N1DdFtUDV1HXsyQ4LwlTM2GG0ggCVzuEvx0YzO6T0P3qFWANdp-UL1KTsh.
Downloading joining block tJa-HIGIiGehnOQlx9Z8Dr8r1YeOlU-eQee6QaK7xWq6S8Yn2EYRLLj2pbGZ00jT.
Downloading joining block tFeHAJBs3lDpoGBr10rmABwJsf2s8y4hXycyZkcadcnJ7TNhxBWvl3smtdheygx9.
Downloading joining block YcppNj34u2xaCm9rJmmcVnSmonGSyylcL8nyPPOAQNMJZIdjn-PtBsF4ZrYav-nh.
Downloading joining block 47AQGrRGzh92mob2giioJJuuxtnMpKEtyi1Wvfh-_MJJGpcgzTSeW-G_PFFeQkAr.
Downloading joining block TYQiiBjrCgSXE68SRHsUll0J-fBJKkG8cbhCYR5kNpR0JfR3yXxEq-4cEAf-L3ed.
Downloading joining block Pu31Z1lEEbmsbwibG3SXBiF7qKijUhMrD9WkjrfWmmRbi5-Z-pVMPnv5VKl6DLeD.
Downloading joining block q_bFxpd8JUZDdqhsPh7sIj9LvJJiNwJFM6njqj-iiktjL17uc9z0bMU82b_O1O2e.
Downloading joining block 9FNbmzo1jEAxjY26bUiEWYHFuMIccVF4_PI2PzSNDmn3D9o87XyYuZiAtcgELWn5.
Downloading joining block G0AY9nEXY5dBRexOqqrO1NyhODqGhXqqvYGqWCmbwog7zpJxtjMU1DLdpj3oZ6mt.
Downloading joining block E70cfGJYT-9-uLASqWufFsqh1Y-2V-gidF8rSwrEaVQTGkT-7PcbdvT6z4Kk_YYM.
Downloading joining block iT2v71HDa9RZ1uV4z-2-6YlzshKZXEOCOuYpBDrfiqJ20O4coZkoLHs999ItuIhU.
Downloading joining block ev_x94__z6tBPThl9UYmklEeS_vP7RSajNU1F-AkQYXULJWobLwmNNXHqmE5_vBB.
Downloading joining block hdpeU8uGJ_daGaWoOCeBNqvLgZI96cxvzbYFFk9UtoJlfVuzUZLYlakESLHfmGSm.
Downloading joining block YicVKzOK5-L1CEPvbd_jiO9rE0EMBEBktU_DDh_jSczDlHKSx1vBRHJBBF3NUs9Y.
Downloading joining block vr3Ea6rBm8vZ2VtSlTbHgGWqSwB-rE-7eoWWd02BlE6SahhqGuIFDceto-YSn2lf.
Downloading joining block V3w6Sq9tKa9_ONoAAMR8gIZp01tpq7Qg_2hAQl31Xq1ynz6b5DnqLIXLGCpB0a4F.
Downloading joining block hFnddbvX_hTEUKCNMoz2rD8mGleFJCE4hVJ9E1VAa_FX45KxKew93mHcsvWBenvn

**Comment by vird** [comment]
You are launching very old 2.4.1.0
Note that install script installs NOT master branch of https://github.com/virdpool/arweave, but miner_experimental_2.4.2.0 (miner_experimental_2.4.4.0 is not working properly)
Use proper install scripts from this repo, you don't need install https://github.com/virdpool/arweave manually and launch manually
