### ISSUE TITLE
When will the new version pool miner release according to Arweave Team's latest releases 2.5.0.0

### ISSUE THREAD

**Issue by strategist922** [virdpool/miner#17]
Hi,

   Will we have new pool miner according to the Arweave Team's latest releases 2.5.0.0?

Thanks and best regards,

James

**Comment by vird** [comment]
virdpool patch for 2.5.0.0 is already tested on testnet and will be available soon for mainnet

**Comment by strategist922** [comment]
It sounds good!
Thanks for your support.

**Comment by vird** [comment]
Currently in master
