### ISSUE TITLE
parameter "enable randomx_large_pages" cannot work in virdpool miner

### ISSUE THREAD

**Issue by strategist922** [virdpool/miner#18]
Dear Support,

         According to section "Configuring large memory pages" in https://docs.arweave.org/info/mining/mining-guide
,the official arweave from arweave.org's repo, it could support parameter "enable randomx_large_pages" when mining.

         But this parameter "enable randomx_large_pages" cannot used after virdpool patch in version 2.4.2? Could it 
possible to enable this parameter in the coming release of virdpool miner?

Thanks in advance!
James

**Comment by vird** [comment]
enable randomx_large_pages is fully supported in all versions see run.sh history
