### ISSUE TITLE
About multiple disk mining

### ISSUE THREAD

**Issue by Hubert51** [virdpool/miner#20]
I noticed on the official website, the AR support multiple hard drives. Do they only support connecting two SSD at the same time? The first one mounted on `/your/dir/chunk_storage` and the second one mounted on `/your/dir/rocksdb`?

**Comment by Hubert51** [comment]
I did a little more exploration. Found that, most of the AR data will store in the `chunk_storage`. So I just decided to put all the AR data into my one SSD.

**Comment by ericmheilman** [comment]
@Hubert51 You'll want to have rocksdb on your ssd as well

**Comment by vird** [comment]
chunk_storage - NVMe or SATA SSD RAID (see calculator for best option for you)
other files SSD or HDD. It should be almost equal performance
