### ISSUE TITLE
How to check hashrate in the miner

### ISSUE THREAD

**Issue by Hubert51** [virdpool/miner#21]
After I executed the `./run.sh`. it only shows these two kinds of messages
```
dataset (weave) sync 96786838836/23421756878273 (  0.41%)
2021-11-22T00:45:33.235Z send new job OK 1JyZp378Gyyr-oU_b7bEhFkoMjMiSzLjw4hGil2q4x27S6odi0vs56lugIYWMMtr 816029
```
Will it show hashrate in the future?

Thank you!

**Comment by vird** [comment]
After arweave node will be connected to network it will specify hashrate in arweave.log (at least) and in stdout
