### ISSUE TITLE
How to set it up to realize that miner is only responsible for mining and not synchronizing data 

### ISSUE THREAD

**Issue by artaime** [virdpool/miner#23]
Hi vird ! The work you do is really awesome!
I have a question now and want your help. 
How to set it up to realize that miner is only responsible for mining and not synchronizing data (Now I have  other machine responsible for synchronizing data).
I look forward to your reply.

**Comment by vird** [comment]
`sync_jobs 0` will stop chunks syncing, but
2 machines will have different datasets. So chunks will be not propagated from one machine to another if you will specify `sync_jobs 0` on your mining machine and keep other machine with default argv.
If you try to run miner on 2 machines, but same dataset (samba, nfs, etc), then it's bad idea. This can work for some time, but then it will corrupt rocksdb at least.
