### ISSUE TITLE
./sync.sh: "Joined the Arweave network successfully." then nothing

### ISSUE THREAD

**Issue by damngod** [virdpool/miner#4]
Hi,

I'm running virdpool on Windows 10 with the Ubuntu app from the MS Store.

When I'm running the sync script, I get the "Joined the Arweave network successfully." but then nothing seems to happen and I cannot see any activity on my computer (CPU, disk, network). Is that expected? Is it possible to monitor the syncing process?

However when I'm running the miner script, I can monitor the syncing process. But from what I understand, this process is slower for syncing.

Thanks.

------------------
Downloading the wallet tree, chunk 29.
Downloaded the wallet tree successfully.
Joined the Arweave network successfully.
------------------

**Comment by vird** [comment]
This is expected behaviour. You can download official arweave node and you will get exactly the same result
