### ISSUE TITLE
where ar files path?

### ISSUE THREAD

**Issue by alexpebody** [virdpool/miner#7]
hello @vird please need help, some days ago i has miner in windows 10 and i have mane TB data of .ar files, now i has install ubuntu 20.04 and i can't find where i must set path to my .ar files?

thank you so much!

**Comment by vird** [comment]
.ar files is used by hpool. They are not compatible with any other miner. There is data_dir, use that option, see run.sh

**Comment by alexpebody** [comment]
Thx @vird so much, but I couldn't understand totally, your miner using peers in run.sh script, I can't find where in run.sh I must set path to my .ar files? Sorry, I a little noob in .ar mining ;-) but in Windows I using more than 6TB files .ar. Maybe your miner using peers, not .ar? And what is process sync.sh, sync with what? If you can please give my simple and short answers.Thx again. Have a nice day.

**Comment by alexpebody** [comment]
As I understood your miner not using .ar files what I using in Windows miner right? But what is data_dir? Miner in Linux sync with peers and downloading some DB again? Please tell me shortly? Thx. )
