### ISSUE TITLE
Set another disk space for DB 8TB

### ISSUE THREAD

**Issue by alexpebody** [virdpool/miner#8]
Dear @vird please help, now I installed ubuntu 20.04 to my 120Gb small ssd and i have second disk like NvME in my system, how i can tell virdpool miner PATH for DB 8TB and set using my second drive for it? Because default sync.sh download DB 8TB to my defauls 120Gb ssd drive (

Sorry for issues and againg THANK YOU SO MUCH!

Have a nice day.

**Comment by vird** [comment]
https://github.com/virdpool/miner/blob/master/run.sh#L33
