### ISSUE TITLE
TUNE your threads

### ISSUE THREAD

**Issue by DrBoBo1** [virdpool/miner#9]
Hi, 
I didn't quite understand how to tune depending on the CPU. Could you write in more detail what these lines mean 
# TUNE your threads. After tuning your startup will be look like this (for 16 core CPU).
# Ratio based on wour weave size
# (8.4/5.4) : 1 = 1.55 : 1
# 10 : 6        = 1.67 : 1 (closest value)
# screen -dmS virdpool_arweave_miner ./arweave/_build/prod/rel/arweave/bin/start port $PORT pool_mine \
#   internal_api_secret $INTERNAL_API_SECRET \
#   $PEERS \
#   stage_one_hashing_threads 10 stage_two_hashing_threads 6 io_threads 4 randomx_bulk_hashing_iterations 20
and give more examples?

**Comment by vird** [comment]
See updated run.sh https://github.com/virdpool/miner/blob/master/run.sh

**Comment by DrBoBo1** [comment]
Thanks!
If the miner is started without additional parameters, what are the default values applied? For example start string only:
screen -dmS virdpool_arweave_miner ./arweave/_build/prod/rel/arweave/bin/start port $PORT pool_mine \
internal_api_secret $INTERNAL_API_SECRET \
$PEERS \

**Comment by vird** [comment]
Default parameters are chosen by arweave node automatically. They are suboptimal. I guess 1:1

**Comment by DrBoBo1** [comment]
If I see rejected in the logs:
2021-09-15T19:26:52.166 Z share accepted:42 rejected:17 stage:0 
this is normal operation? Or it says that the parameters are not selected optimally?

**Comment by vird** [comment]
I have same rejected. 8-12% is normal.

**Comment by DrBoBo1** [comment]
Ok.
There are 2 nodes connected to the pool (use one wallet), why on https://ar.virdpool.com/#/address/ I see only 1 worker? 
And where can I change the name of "default_worker"?

**Comment by vird** [comment]
https://github.com/virdpool/miner/blob/master/run.sh#L118

**Comment by DrBoBo1** [comment]
I observe the unstable operation of the miner, after a while appear in the log "arweave.log" the messages: 
Miner spora rate: 430 h/s, recall bytes calculated/s: 3348, MiB/s read: 0, the round lasted 60 seconds 
... the round lasted 120 seconds .
... the round lasted 240 seconds 
and so on, the time of "the round lasted XXXX seconds" is constantly increasing. 
It seems that the miner is hanging. What can this be related to?

**Comment by vird** [comment]
Pls use arweave miners discord for questions and perf tuning recipes https://discord.gg/Py5pvFSg
Lots of information there.
Also your last question is not about this miner, but about arweave node in general. I give only very limited support for general arweave node question
